spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/sms
spring.datasource.username=postgres
spring.datasource.password=pass
spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=localhost
spring.data.redis.port=6379