spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/sms
spring.datasource.username=postgres
spring.datasource.password=pass
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always